import {lazy,Suspense,useCallback,useEffect,useState} from 'react';
import {Link,Route,Routes,useLocation,useNavigate} from 'react-router-dom';
import {ArrowLeft,ArrowRight,ArrowUpRight,Check,MoveRight,SkipForward} from 'lucide-react';
import {AnimatePresence,motion} from 'framer-motion';
import Guide from './components/avatar/Guide';
import Challenge from './features/challenge/Challenge';
import {chapters,pathItems} from './content/story';
import {links} from './content/links';
const FlowStudio=lazy(()=>import('./features/flow-studio/FlowStudio'));
const Orb=lazy(()=>import('./features/orb/Orb'));
const progressKey='flow-studio-journey-v1';
function useProgress(){const [completed,setCompleted]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem(progressKey)||'[]')}catch{return []}});const mark=useCallback((route:string)=>{setCompleted(old=>{if(old.includes(route))return old;const next=[...old,route];localStorage.setItem(progressKey,JSON.stringify(next));return next})},[]);return{completed,mark}}
function Layout({children,completed}:{children:React.ReactNode;completed:string[]}){const location=useLocation();return <div className="app-shell"><header className="topbar"><Link className="brand" to="/" aria-label="back to the start"><span className="brand-mark">lg<span>.</span></span><span className="brand-sep"/> an application that got out of hand</Link><div className="top-right"><span className="status-dot"/> interactive note <Link className="map-link" to="/journey">the path <ArrowUpRight size={14}/></Link></div></header><div className="page-wrap">{children}</div><footer className="site-foot"><span>unofficial concept by luvish gulati. based on public blue machines information and my own getvocal-platform experience. not affiliated with blue machines.</span><span>{completed.length} / 9 explored</span></footer>{location.pathname!=='/'&&<Link className="floating-path" to="/journey">path <span>↗</span></Link>}</div>}
function Intro(){return <main className="intro-screen"><div className="intro-side"><span className="section-index">00 / intro</span><div className="intro-guide"><Guide state="walking" size={112}/><span className="guide-speech">hey blue machines</span></div></div><div className="intro-content"><p className="eyebrow">a short, interactive application · ~2 min</p><h1>im luvish.</h1><p>this was supposed to be a normal job application.</p><p>then i got distracted.</p><div className="actions"><Link className="btn primary" to="/journey">start the rabbit hole <ArrowRight size={18}/></Link><Link className="text-link" to="/flow-studio">skip to the idea <SkipForward size={15}/></Link></div></div><div className="intro-corner">01 / 08 <span>an idea before the résumé</span></div></main>}
function Journey({completed}:{completed:string[]}){return <main className="journey-screen"><div className="journey-intro"><p className="eyebrow">the path / choose your own shortcut</p><h1>follow the thought.</h1><p>eight short checkpoints. no locks. skip ahead if the interesting bit is the prototype.</p><Link to="/flow-studio" className="text-link">go straight to flow studio <ArrowUpRight size={16}/></Link></div><div className="journey-path" aria-label="journey checkpoints">{pathItems.map((item,i)=><Link key={item.to} to={item.to} className={`path-stop stop-${i%4} ${completed.includes(item.to)?'complete':''}`}><span className="path-node">{completed.includes(item.to)?<Check size={18}/>:item.num}</span><span className="path-name">{item.name}</span></Link>)}<div className="path-guide"><Guide state="pointing" size={88}/><span>pick anywhere. i wont gatekeep.</span></div></div></main>}
function GraphStory({variant}:{variant:1|2|3}){const [collapsed,setCollapsed]=useState(false);return <div className={`story-visual visual-${variant}`}><div className="visual-top"><span>illustrative workflow</span><span>{variant===3?'too many tiny steps':'a call in context'}</span></div>{variant===3?<><div className={`micro-grid ${collapsed?'is-collapsed':''}`}>{['ask id','ask issue','clarify issue','ask urgency','confirm details','follow up'].map(x=><span key={x}>{x}</span>)}</div><button className="btn secondary collapse-btn" onClick={()=>setCollapsed(v=>!v)}>{collapsed?'expand micro-steps':'collapse the conversation'} <MoveRight size={15}/></button>{collapsed&&<div className="llm-box"><strong>llm node</strong><span>goal: understand the issue</span><span>collect: id · issue · urgency</span><span>then return to the graph →</span></div>}</>:<div className="simple-graph">{(variant===1?['incoming call','opener','understand customer','condition','action / follow-up']:['verify customer','fetch account','condition','payment / service flow','response']).map((node,i)=><div className="graph-step" key={node}><span className="graph-count">0{i+1}</span><strong>{node}</strong>{i<4&&<span className="graph-connector" aria-hidden="true"/>}</div>)}</div>}<p className="visual-foot">demo structure only. no client data or platform internals.</p></div>}
function SystemsVisual(){return <div className="systems-visual"><div className="visual-top"><span>public direction · interpreted</span><span>not internal architecture</span></div><div className="systems-rail">{['voice','speech to text','reasoning + journey','tools / systems','text to speech','customer'].map((x,i)=><div className="system-item" key={x}><span>{String(i+1).padStart(2,'0')}</span><strong>{x}</strong></div>)}</div><div className="system-pills">{['agent studio','enterprise integrations','guardrails','analytics','deployment options'].map(x=><span key={x}>{x}</span>)}</div></div>}
function Stage({id,mark}:{id:number;mark:(s:string)=>void}){const chapter=chapters[id-1],navigate=useNavigate();const next=id===5?'/flow-studio':`/stage/${id+1}`;useEffect(()=>{mark(`/stage/${id}`)},[id,mark]);return <main className="story-screen"><div className="story-left"><Link className="back-link" to="/journey"><ArrowLeft size={16}/> all checkpoints</Link><p className="eyebrow">{chapter.kicker}</p><h1>{chapter.title}.</h1><p className="story-teaser">{chapter.teaser}</p>{chapter.body.map(text=><p className="story-body" key={text}>{text}</p>)}{id===5&&<div className="source-links"><a href={links.blueMain} target="_blank" rel="noreferrer">public platform ↗</a><a href={links.blueRole} target="_blank" rel="noreferrer">the role ↗</a><a href={links.blueSystems} target="_blank" rel="noreferrer">systems thinking ↗</a></div>}<div className="chapter-next"><span>{chapter.aside}</span><button className="btn primary" onClick={()=>navigate(next)}>{id===5?'try flow studio':'continue'} <ArrowRight size={17}/></button></div></div><div className="story-right">{id===4?<Challenge/>:id===5?<SystemsVisual/>:<GraphStory variant={id===3?3:id===1?1:2}/>}</div></main>}
function Me(){return <main className="me-screen"><div className="me-guide"><Guide state="celebrating" size={100}/><span className="guide-speech">almost forgot why i made this 😭</span></div><p className="eyebrow">08 / oh right, the job</p><h1>this was technically supposed to be a job application.</h1><p>im not going to pretend ive spent 5 years doing this. i havent. but ive worked close to this problem before, built voice agents on GetVocal's platform, and shipped software across product and engineering work.</p><p>so instead of writing “fast learner” on another résumé, i figured id show you how i think.</p><div className="experience-strip"><span><strong>growthx</strong> software engineering</span><span><strong>pink unicorn</strong> client voice ai workflows</span><span><strong>henry</strong> personal agent automation</span><span><strong>kelly</strong> local voice ai experiments</span></div><div className="actions"><a className="btn primary" href={links.email}>give me a problem <ArrowRight size={17}/></a><a className="text-link" href={links.resume} target="_blank" rel="noreferrer">resume ↗</a><a className="text-link" href={links.github} target="_blank" rel="noreferrer">github ↗</a><a className="text-link" href={links.portfolio} target="_blank" rel="noreferrer">portfolio ↗</a></div></main>}
export default function App(){const location=useLocation(),{completed,mark}=useProgress();useEffect(()=>{if(location.pathname!=='/')mark(location.pathname)},[location.pathname,mark]);return <Layout completed={completed}><AnimatePresence mode="wait"><motion.div key={location.pathname} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-6}} transition={{duration:.22}}><Routes location={location}><Route path="/" element={<Intro/>}/><Route path="/journey" element={<Journey completed={completed}/>}/>{[1,2,3,4,5].map(id=><Route key={id} path={`/stage/${id}`} element={<Stage id={id} mark={mark}/>}/>)}<Route path="/flow-studio" element={<Suspense fallback={<div className="loading">loading the prototype…</div>}><FlowStudio/></Suspense>}/><Route path="/orb" element={<Suspense fallback={<div className="loading">loading the experiment…</div>}><Orb/></Suspense>}/><Route path="/me" element={<Me/>}/><Route path="*" element={<Intro/>}/></Routes></motion.div></AnimatePresence></Layout>}
