import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowLeft,ArrowRight,Volume2,VolumeX} from 'lucide-react';
const prompts=[{label:'where is my order?',reply:'i can help check that. first, what is your order id?',phase:'collecting order id'},{label:'i want to change a delivery',reply:'sure. tell me the order id and the new delivery date you have in mind.',phase:'collecting requested date'},{label:'the account system is down',reply:'i cannot verify account details while the service is unavailable. i can arrange a human follow-up instead.',phase:'safe fallback'}];
export default function Orb(){const [selected,setSelected]=useState<number|null>(null),[sound,setSound]=useState(false);
  useEffect(()=>()=>window.speechSynthesis?.cancel(),[]);
  function choose(i:number){window.speechSynthesis?.cancel();setSelected(i);if(sound&&'speechSynthesis'in window){const line=new SpeechSynthesisUtterance(prompts[i].reply);line.lang='en-IN';line.rate=.96;window.speechSynthesis.speak(line)}}
  return <main className="orb-page"><Link className="back-link" to="/flow-studio"><ArrowLeft size={16}/> back to flow studio</Link><p className="eyebrow">07 / a second interaction thought</p><h1>what if the page talked back?</h1><p>not instead of the workflow. on top of it. a lightweight voice-first surface where the underlying state is still visible.</p><div className="orb-interaction"><div className={`orb-core ${selected!==null?'speaking':''}`} aria-hidden="true"><span/><span/><span/></div><div className="orb-copy"><span className="eyebrow">try a sample request</span><h2>{selected===null?'pick something a customer might say.':prompts[selected].reply}</h2><p>{selected===null?'no microphone or server is needed for this concept.':'journey state: '+prompts[selected].phase}</p></div></div><div className="orb-controls"><button className="btn secondary" onClick={()=>{setSound(v=>!v);window.speechSynthesis?.cancel()}} aria-pressed={sound}>{sound?<Volume2 size={17}/>:<VolumeX size={17}/>} browser voice {sound?'on':'off'}</button>{prompts.map((x,i)=><button key={x.label} className={selected===i?'orb-option chosen':'orb-option'} onClick={()=>choose(i)}>{x.label}</button>)}</div><p className="orb-note">illustrative scripted responses. browser speech is optional and may vary by device. this is not live AI or a Blue Machines feature.</p><Link className="btn primary" to="/me">meet the person behind this <ArrowRight size={16}/></Link></main>
}
